
#内置服务器端口
server:
  port: 7778

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://123.60.176.255/shuqgdb?serverTimezone=Asia/Shanghai
    url: jdbc:mysql://127.0.0.1/material?serverTimezone=Asia/Shanghai
    username: root
    password: root
#    password: mysql_1234
    type:  com.alibaba.druid.pool.DruidDataSource
    initialSize: 5 #初始化时建立物理连接的个数
    minIdle: 1 #最小连接池数量
    maxActive: 20 #最大连接池数量
  mail:
    host: smtp.qq.com
    username: 3287033742 #发送方qq号
    password: ocqbxxywrsmadahj  #授权码
#    default-encoding: utf-8
#    protocol: smtps
#    test-connection: true
#    port: 465
#    properties:
#      mail:
#        smtp:
#          socketFactort:
#            port: 465
#            class: javax.net.ssl.SSLSocketFactory
#            fallback: false
#        auth: true
#        starttls:
#          enable: true
#          required: true
  main:
    allow-circular-references: true #开始支持spring循环依赖
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: 123.60.176.255
    port: 6379
    password: redis_1234
    database: 0
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
      timeout: 5000ms # 连接超时时间（毫秒）
  rabbitmq:
    host: 123.60.176.255 # 主机名
    port: 5672 # 端口
    virtual-host: /shuqg # 虚拟主机
    username: shuqg # 用户名
    password: shuqg # 密码


mybatis:
  type-aliases-package: com.snut.material.model # 别名
  mapper-locations:
    - classpath:mappers/message/*Mapper.xml  # 扫描映射文件
    - classpath:mappers/front/*Mapper.xml  # 扫描映射文件
    - classpath:mappers/user/*Mapper.xml  # 扫描映射文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 日志实现
    map-underscore-to-camel-case: true # 驼峰格式转换
    cache-enabled: true # 缓存

logging:
  level:
    springboot: trace #日志级别   debug<info<warn<error
#  file:
#    name: /opt/java/land7778/log.log
#    name: D:/log/log.log  #日志文件输出位置


user:
  name: 张三
  age: 20